### ISSUE TITLE
Cannot make it work with NextJS

### ISSUE THREAD

**Issue by varKeytrap** [vidstack/vidstack#666]
I followed the official tutorial [here](https://www.vidstack.io/docs/player/react/getting-started/quickstart/#select-js-library)
Installed dependencies with `npm i lit @vidstack/player@next @vidstack/player-react@next`

Finally I `npm run dev` and this what happens in vscode terminal:

```
TypeError: this._$Ek is not a function
    at VideoElement.update (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit/reactive-element/reactive-element.js:6:5362)
    at LitElementRenderer.connectedCallback (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:31:42)
    at renderTemplateResult (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit-labs/ssr/lib/render-lit-html.js:464:30)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit-labs/ssr/lib/render-lit-html.js:355:16)
    at renderValue.next (<anonymous>)
    at renderTemplateResult (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit-labs/ssr/lib/render-lit-html.js:401:24)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///C:/Users/eugen/Downloads/test/my-app/node_modules/@lit-labs/ssr/lib/render-lit-html.js:355:16)
    at renderValue.next (<anonymous>)
```

The app was created with `npx create-next-app`

Here's package.json:
![image](https://user-images.githubusercontent.com/17864005/180030612-6b5ce660-baa9-45a5-9549-1c44bb59a819.png)

Here's the full error :
<details>
  <summary>Click to expand</summary>
<img src="https://user-images.githubusercontent.com/17864005/180031398-ecebdb35-547f-461a-b030-97b317626a55.png" />
</details>

**Comment by mihar-22** [comment]
Yep I can repro now after upgrading `lit`. It's an upstream bug unfortunately, looking into it now.

**Comment by mihar-22** [comment]
Should be fixed now @varKeytrap, let me know if there's any problems on `1.6.2`. One thing you'll need to add is `data-video` attribute to the `<video>` element. I have absolutely no idea where it's coming from on the server but it's not Vidstack.

```
<!-- Add this attribute -->
<video data-video="0">
```
